modLoader="javafml"
loaderVersion="[2,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
A mod that reworks Minecraft base mechanics, to make the game
feel more balanced. The main mechanics are Food, Enchantments and Potions.
Greed lets you experience an unsatiable thirst for knowledge.
'''

[[mixins]]
config="mixins.greed.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
